---
- hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - curl
          - docker.io
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: true

    - name: Disable swap
      command: swapoff -a
      ignore_errors: true

    - name: Keep swap off between reboots
      replace:
        path: /etc/fstab
        regexp: '^\s*([^#\s].*?\s+swap\s+.*)$'
        replace: '# \1'
      ignore_errors: true

- hosts: master
  become: true
  tasks:
    - name: Initialize Kubernetes Master
      shell: |
        kubeadm init --pod-network-cidr=192.168.0.0/16
      register: k8s_init
      ignore_errors: true

    - name: Create kube config directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: 0700

    - name: Copy kube config to user
      command: cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config

    - name: Apply Calico CNI Plugin
      shell: |
        kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: Get Join Command
      shell: kubeadm token create --print-join-command
      register: join_command
      delegate_to: master

- hosts: workers
  become: true
  tasks:
    - name: Join Kubernetes Cluster
      shell: "{{ hostvars['k8s-node-1'].join_command.stdout }}"
      ignore_errors: true
